apiVersion: v1
kind: Service
metadata:
  labels:
    mirror.linkerd.io/exported: "true"
  name: nginx-invalid-deploy-svc
  namespace: default
spec:
  clusterIP: None
  selector:
    app: nginx-invalid-deploy
  sessionAffinity: None
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-invalid-deploy
spec:
  selector:
    matchLabels:
      app: nginx-invalid-deploy
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-invalid-deploy
    spec:
      containers:
      - name: nginx
        image: nginx

